# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

shared:
  site_name: 'Nada'
  facebook_url: 'https://www.facebook.com/groups/11319949545'
  twitter_url: 'https://twitter.com/nadamagazineuk'
  instagram_url: 'https://www.instagram.com/nadamagazineuk'
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>

development:
  secret_key_base: dcc219d729d7fa48ef4f7431613bcb31225b8b927a9d40e0ad89cbdb9477d0e9dae915895d243bfc737ec3554868d0d35b71e7c246fd9c314c969a4c3614cd41

test:
  secret_key_base: a11a9ff54d7ba0af301a4dea60dbfbc4c30f07d82fbc570ae44a6e74a8efe3d2a9e561580b849833a601eec2f1123e99950ae5f4f98849087898ec143f0ebe04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  canonical_host: 'nadadance.co.uk'
